#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$artisan = new TwoThirds\ArtisanAnywhere\Artisan(__DIR__);

$artisan->setConfig([
    'test-suite' => require('./vendor/two-thirds/laravel-test-suite/config/default.php'),
    'test-suite.phpunit.timeout' => 60 * 5,
    'test-suite.php-cs-fixer.folders' => ['./src', './tests/Exceptions', './tests/Integration', './tests/Traits', './tests/Unit'],
    'test-suite.phpmd.folders' => ['./src', './tests/Exceptions', './tests/Integration', './tests/Traits', './tests/Unit'],
]);

$artisan->registerCommands([
    TwoThirds\TestSuite\Console\RunTestCommand::class,
    TwoThirds\TestSuite\Console\RunPhpUnitCommand::class,
    TwoThirds\TestSuite\Console\RunPhpCsFixerCommand::class,
    TwoThirds\TestSuite\Console\RunPhpmdCommand::class,
    Laravel\Tinker\Console\TinkerCommand::class,
]);

exit($artisan->handle());
