name: Test Suite

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: PHPUnit
      run: php artisan test:phpunit --without-tty

    - name: PHP CS Fixer
      run: php artisan test:php-cs-fixer --without-tty
      
    - name: PHP Mess Detector
      run: php artisan test:phpmd --without-tty
